Add Support for creating PPPC & System Extensions and update Exports and ESlint
pliancy/addigy-node pull request #30
Opened 2021-06-23 22:35 UTC by santese

-Added Support for creating PPPC MDM Config
-Added Support for creating System Extension MDM Config
- Update to Pliancy ESLint Config
- Move Types to Separate file
- Export Types and Remove Default Export of Addigy Class

2021-06-23 22:53 UTC, CalebAlbers requested changes
Nice work adding the PPPCs, system extensions, and thanks for updating eslint.

Can you write a quick example in the README for creating PPPCs, Sys Extensions, and KEXTs? Given we're using an interface that is modified (normalized) from what Addigy uses, it'll be good to provide docs for people on usage.

2021-06-23 22:53 UTC, CalebAlbers commented on .github/workflows/npm-publish.yml
> +          registry-url: 'https://npm.pkg.github.com'
Let's publish to NPM instead of GH Packages for this one

2021-06-23 22:53 UTC, CalebAlbers commented on package.json
> +    "@pliancy/eslint-config-ts": "0.0.5",
We can move this and Typescript to dev deps

2021-06-23 22:56 UTC, santese commented on package.json
> +    "@pliancy/eslint-config-ts": "0.0.5",
> Nice work adding the PPPCs, system extensions, and thanks for updating eslint.
> 
> Can you write a quick example in the README for creating PPPCs, Sys Extensions, and KEXTs? Given we're using an interface that is modified (normalized) from what Addigy uses, it'll be good to provide docs for people on usage.

Yeah will do and I'll also add some decorators as well

2021-06-24 20:46 UTC, CalebAlbers reviewed
Thank you for writing the docs on the new commands and being through on the JSDoc side as well for those! I added a note about removing ESLint dev deps.

Great work on this, as always! Feel free to merge and publish a major release.

2021-06-24 20:46 UTC, CalebAlbers commented on package.json
> +        "eslint-plugin-unused-imports": "^1.0.1",
The ESLint dev deps can be removed - they are child deps of the pliancy ESLint onfig. Same with `prettier`

2021-06-24 20:54 UTC, santese commented
Update to 2.0.0

2021-06-24 20:55 UTC, merged